### ISSUE TITLE
The definition of Stateful and Stateless is not correct

### ISSUE THREAD

**Issue by duypham9895** [learning-zone/react-interview-questions#15]
`A React component can be either stateful or stateless. Stateful components are of the class type, while stateless components are of the function type.`

I do not think the term is correct in React context, I think `A stateful component is a component that holds some state. Stateless components, by contrast, have no state`.

**Comment by learning-zone** [comment]
Hi @duypham9895 

Please mention the question here.

**Comment by duypham9895** [comment]
In chapter 4 - React Component, we have a question [What are React [components?](https://github.com/learning-zone/react-interview-questions#q-what-are-react-components), and in the answer to this question, you mention `Stateless vs Stateful` but I do not think your answer is correct. Because in the React context, `A stateful component is a component that holds some state. Stateless components, by contrast, have no state`, it is not about class or function. @learning-zone

**Comment by learning-zone** [comment]
Hi @duypham9895 

You can raise a PR for the same,  thanks

**Comment by duypham9895** [comment]
> Hi @duypham9895
> 
> How do you define state for functional component in react?

For me, I will use a hook `useState()` to define state in my functional component
